# Generated by Django 2.1 on 2018-08-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='files/images/singers/')),
                ('birthday', models.DateTimeField(blank=True)),
                ('genre', models.ManyToManyField(to='music.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('ogg', 'OGG')], max_length=255)),
                ('created', models.DateField()),
                ('duration', models.TimeField()),
                ('file1', models.FileField(blank=True, upload_to='files/songs/')),
                ('descrtion1', models.CharField(blank=True, max_length=32)),
                ('file2', models.FileField(blank=True, upload_to='files/songs/')),
                ('descrtion2', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(upload_to='files/images/songs')),
                ('views', models.PositiveIntegerField(default=0)),
                ('genre', models.ManyToManyField(to='music.Genre')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
