# Generated by Django 2.1 on 2018-09-22 17:24

from django.db import migrations, models
import django.db.models.deletion
import music.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file1', models.FileField(blank=True, upload_to=music.models.album_directory_path, verbose_name='File 320')),
                ('file2', models.FileField(blank=True, upload_to=music.models.album_directory_path, verbose_name='File 128')),
                ('image', models.ImageField(upload_to=music.models.album_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='files/images/singers/')),
                ('birthday', models.DateTimeField(blank=True)),
                ('genre', models.ManyToManyField(to='music.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(allow_unicode=True, max_length=80)),
                ('created', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=5)),
                ('file1', models.FileField(blank=True, upload_to=music.models.song_directory_path, verbose_name='File 320')),
                ('file2', models.FileField(blank=True, upload_to=music.models.song_directory_path, verbose_name='File 128')),
                ('image', models.ImageField(upload_to=music.models.song_directory_path)),
                ('views', models.PositiveIntegerField(default=0)),
                ('lyrics', models.TextField(blank=True, default='')),
                ('genres', models.ManyToManyField(to='music.Genre')),
                ('languages', models.ManyToManyField(to='music.Language')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(to='music.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'singer')},
        ),
    ]
