# Generated by Django 2.1 on 2018-08-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180822_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='genre',
            new_name='genres',
        ),
    ]
