# Generated by Django 2.1 on 2018-08-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180823_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='descrtion1',
        ),
        migrations.RemoveField(
            model_name='song',
            name='descrtion2',
        ),
    ]
