# Generated by Django 2.1 on 2018-08-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180823_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='layrics',
            field=models.TextField(blank=True, default=''),
        ),
    ]
