# Generated by Django 2.1 on 2018-08-24 06:56

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song_layrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file1',
            field=models.FileField(blank=True, upload_to=music.models.song_directory_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='file2',
            field=models.FileField(blank=True, upload_to=music.models.song_directory_path),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to=music.models.song_directory_path),
        ),
    ]
