# Generated by Django 2.1 on 2018-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20180824_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='aaaaaaaa', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'singer')},
        ),
    ]
