# Generated by Django 2.1 on 2018-08-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20180824_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=80),
        ),
    ]
