# Generated by Django 2.1 on 2018-08-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20180825_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='layrics',
            new_name='lyrics',
        ),
    ]
