# Generated by Django 2.1 on 2018-08-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20180825_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='type',
        ),
        migrations.AlterField(
            model_name='song',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
