# Generated by Django 2.1 on 2018-08-31 06:23

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_song_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='file1',
            field=models.FileField(blank=True, upload_to=music.models.song_directory_path, verbose_name='File 320'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file2',
            field=models.FileField(blank=True, upload_to=music.models.song_directory_path, verbose_name='File 128'),
        ),
        migrations.AddField(
            model_name='song',
            name='languages',
            field=models.ManyToManyField(to='music.Language'),
        ),
    ]
