# Generated by Django 2.1 on 2018-09-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images/advertisements')),
            ],
        ),
    ]
