# Generated by Django 2.1 on 2018-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('a', 'A'), ('b1', 'B1'), ('b2', 'B2'), ('c', 'C'), ('d1', 'D1'), ('d2', 'D2'), ('e', 'E')], default='A', max_length=2),
            preserve_default=False,
        ),
    ]
